export default {
    EnterNumber: "Enter your mobile number for a better travel{'\n'}experience at the airport",
    skip: "Skip",
    preferences: "preferences",
    EnterOtp: "Enter the 4 digit OTP",
    hi: "Hi",
    welcometoHoi: "Welcome to HOI",
    question: "Would you like to automatically your flights?",
    description: "Just sync your email and you don’t need to add flight manually anymore",
    linkmymail: "Yes, link my email",
    later: "I will do it later",
    manualFlightAdd: "You can also manually add a flight anytime",
    scanDescription: "Scan, take a picture or search flight to add your travel manually",
    addTravel: "Add Travel",
    pleaseAddName: "Please add your name as per your ID proof that you use for travelling",
    internetConnection: "Please check your internet",
    fetchingLocation: "Fetching Location ...",
    ON_DELETE_LOCATION: "ON DELETE LOCATION",
    FETCH_LOCATION_API: "FETCH_LOCATION_API",
    SHOW_COMMON_ALERT: "SHOW_COMMON_ALERT",
    SHOW_COMMON_ERROR: "SHOW_COMMON_ERROR",
    ON_FETCH_API_VERSION_CONTROL: "ON_FETCH_API_VERSION_CONTROL",
    FETCH_PROFILE_API: "FETCH_PROFILE_API",
    FORCE_UPDATE: "FORCE_UPDATE",
    FETCH_UPCOMING_TRIP: "FETCH_UPCOMING_TRIP",
    FETCH_TRIP_DETAILS: "FETCH_TRIP_DETAILS",
    NameInptWarning: "Please enter valid name",
    EmailInputWarning: "Please enter valid Email ",
    MobileNoInptWarning: "Please enter valid mobile number",
    MessageInputWarning: "Please type minimum 20 letters in message ",
    OnlyAlphabets: "Provided message is not supported. please try with different letters",
    ON_USER_ID_FETCHED: "ON_USER_ID_FETCHED",
    ON_USER_LOGIN_OTHERDEVICE: "ON_USER_LOGIN_OTHERDEVICE",
    ON_REFRESH_TOKEN: "ON_REFRESH_TOKEN",
    OnCartFlightSelected: "OnCartFlightSelected",
    ONSELECTCOUPON: "ONSELECTCOUPON",
    CART_COUNT: "CART_COUNT",
    ON_TRAVEL_RATED: "ON_TRAVEL_RATED",
    ON_FLIGHT_ADDED: "ON_FLIGHT_ADDED",
    ON_CHANGE_TERMINAL_FILTERS: "ON_CHANGE_TERMINAL_FILTERS",
    ON_EXPLORE_CHANGE_TERMINAL_FILTERS: "ON_EXPLORE_CHANGE_TERMINAL_FILTERS",
    ON_COUNTRY_SELECTED: "ON_COUNTRY_SELECTED",
    ON_REFRESH_CATEGORIES: "ON_REFRESH_CATEGORIES",
    DATE_ERROR_MSG: "Please select valid Date"
  };
  